apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: app1
          image: cloudwithvarjosh/cwvj-app1:v1.0.0
          ports:
            - containerPort: 5000